//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_6___7.WSDLServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSDLServices.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWordsFromFile", ReplyAction="http://tempuri.org/IService1/GetWordsFromFileResponse")]
        string GetWordsFromFile(System.IO.Stream f1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWordsFromFile", ReplyAction="http://tempuri.org/IService1/GetWordsFromFileResponse")]
        System.Threading.Tasks.Task<string> GetWordsFromFileAsync(System.IO.Stream f1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSimilarityScore", ReplyAction="http://tempuri.org/IService1/GetSimilarityScoreResponse")]
        string GetSimilarityScore(string s, string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSimilarityScore", ReplyAction="http://tempuri.org/IService1/GetSimilarityScoreResponse")]
        System.Threading.Tasks.Task<string> GetSimilarityScoreAsync(string s, string s2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Assignment_6___7.WSDLServices.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Assignment_6___7.WSDLServices.IService1>, Assignment_6___7.WSDLServices.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWordsFromFile(System.IO.Stream f1) {
            return base.Channel.GetWordsFromFile(f1);
        }
        
        public System.Threading.Tasks.Task<string> GetWordsFromFileAsync(System.IO.Stream f1) {
            return base.Channel.GetWordsFromFileAsync(f1);
        }
        
        public string GetSimilarityScore(string s, string s2) {
            return base.Channel.GetSimilarityScore(s, s2);
        }
        
        public System.Threading.Tasks.Task<string> GetSimilarityScoreAsync(string s, string s2) {
            return base.Channel.GetSimilarityScoreAsync(s, s2);
        }
    }
}
